apiVersion: v1
kind: Pod
metadata:
 name: service-demo
# these lables are used to 
 labels:
  project: roboshop
  component: frontend
  environment: dev
spec:
 containers:
 - name: nginx
   image: nginx